### ISSUE TITLE
How to create the *_PHN.txt for specific sentences?

### ISSUE THREAD

**Issue by a312863063** [Dianezzy/ParaLip#1]
Hi, I want the mouth to say sentences I specify, so I need to make phoneme files like *_PHN.txt in the timit directory. 
I would like to ask if there is any tool to do this?

**Comment by iloveOREO** [comment]
> Hi, I want the mouth to say sentences I specify, so I need to make phoneme files like *_PHN.txt in the timit directory. I would like to ask if there is any tool to do this?

Hi! Did you find the way to create the *PHN.txt for specific sentences?

**Comment by anuragdeshmukh** [comment]
> 

Hi were you able to find any resolution to this?
